[mgr]
ratio = [1, 2, 6]  # bump the last number for a wider preview
show_hidden = true

[[plugin.prepend_previewers]]
url = "*/"
run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"'
[[plugin.prepend_previewers]]
mime = "image/*"
run = 'sh -c "chafa -f symbols \"$1\""'
